remote_theme: JS-DevTools/gh-pages-theme

title: Friendly Project Name
logo: https://jstools.dev/img/logos/logo.png

author:
  twitter: JSDevTools

google_analytics: UA-68102273-3

twitter:
  username: JSDevTools
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: https://jstools.dev/img/logos/card.png
  - scope:
      path: "test/**/*"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
